import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { FaSearch } from "react-icons/fa";
import Image from "next/image";
import { conteudo } from ".//api/conteudo";
import Link from "next/link";
import Cabecalho from "./api/cabecalho";
import { Icon } from "@iconify/react";

export default function Home() {
  const { banner, superMario } = conteudo;
  const { consoles } = conteudo;
  const { diversos } = conteudo;

  return (
    <header>
      <Head>
        <title>PlayerOne</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="cabecalho">
        <Link className="cabecalho_link" href="/">
          <Icon color="#628FD9" width="3rem" icon="ph:game-controller" />
          <h1>
            Player<span>One</span>
          </h1>
        </Link>
        <div className="login">
          <Link className="link_login" href="/login">
            <button>Login</button>
          </Link>
        </div>
      </div>

      <div className={styles.banner}>
        <div className={styles.bannerOverlay}></div>
        <Image
          className={styles.bannerImage}
          src={banner.src}
          alt="Chápeu do Mario"
        />
        <h1>{banner.title}</h1>
        <p>{banner.description}</p>
        <button>Super Mario</button>
      </div>

      <div className={styles.conteudo}>
        <h1>Super Mario</h1>
        <div className={styles.conteudoContainer}>
          {superMario.map((item, index) => (
            <div className={styles.conteudoItem} key={index}>
              <Image
                className={styles.imagens}
                src={item.src}
                alt={item.text}
                width={item.width}
                height={item.height}
              />
              <p>{item.text}</p>
              <p>Preço: {item.price}</p>
            </div>
          ))}
        </div>

        
      </div>

      <div className="rodapeInicial">
        <div className={styles.alerta}>
          <h1>Faça login para visualizar a pagina completa!</h1>
        </div>
        <Link className="cabecalho_linkPaginaINicial" href="/">
          <Icon color="#628FD9" width="3rem" icon="ph:game-controller" />
          <h1>
            Player<span>One</span>
          </h1>
        </Link>

        <h4>
          Desenvolvido por{" "}
          <Link
            className="linkRodape"
            href="https://www.linkedin.com/in/isis-souza-979163295/"
          >
            {" "}
            Isis Guimarães{" "}
          </Link>
          | 2023 ♡
        </h4>
      </div>
    </header>
  );
}
