import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { FaSearch } from "react-icons/fa";
import Image from "next/image";
import { conteudo } from "./api/conteudo";
import Link from "next/link";
import Cabecalho from "./api/cabecalho";

export default function Home() {
  const { banner, superMario } = conteudo;

  return (
    <header>
      <Head>
        <title>PlayerOne</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="cabecalho">
        <Link className="cabecalho_link" href="/">
          <h1>
            Player<span>One</span>
          </h1>
        </Link>
        <div className="search">
          <input className="input" type="text" placeholder="Pesquisa" />
          <FaSearch
            style={{
              width: "1em",
              height: "1em",
              color: "#A7C0EA",
            }}
          />
        </div>
      </div>

      <div className={styles.banner}>
        <Image className={styles.banner} src={banner.src} />
        <h1>{banner.title}</h1>
        <p>{banner.description}</p>

        <button>Super Mario</button>
      </div>

      <div className={styles.conteudo}>
        <h1>Super Mario</h1>
        <div className={styles.conteudoContainer}>
          {superMario.map((item, index) => (
            <div className={styles.conteudoItem} key={index}>
              <Image
                className={styles.imagens}
                src={item.src}
                width={item.width}
                height={item.height}
              />
              <p>{item.text}</p>
              <p>Preço: {item.price}</p>
            </div>
          ))}
        </div>
      </div>
    </header>
  );
}
