import Head from "next/head";
import { Icon } from "@iconify/react";
import styles from "@/styles/Home.module.css";
import { FaGamepad, FaSearch } from "react-icons/fa";
import Image from "next/image";
import { conteudo } from "./api/conteudo";
import Link from "next/link";
import Cabecalho from "./api/cabecalho";
import { useState } from "react";

export default function Home() {
  const { banner, superMario, consoles, diversos } = conteudo;
  const [busca, setBusca] = useState("");

  const filtrarConteudo = (categoria) =>
    categoria.filter((item) =>
      item.text.toLowerCase().includes(busca.toLowerCase())
    );

  const marioFiltrado = filtrarConteudo(superMario);
  const consolesFiltrados = filtrarConteudo(consoles);
  const diversosFiltrados = filtrarConteudo(diversos);

  return (
    <header>
      <Head>
        <title>PlayerOne</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="cabecalhoPaginaInicial">
        <Link className="cabecalho_linkPaginaINicial" href="/">
          <Icon color="#628FD9" width="3rem" icon="ph:game-controller" />
          <h1>
            Player<span>One</span>
          </h1>
        </Link>
        <div className="searchPaginaInicial">
          <input
            value={busca}
            onChange={(ev) => setBusca(ev.target.value)}
            className="inputPaginaInicial"
            type="text"
            placeholder="Pesquisa"
          />
          <FaSearch
            style={{
              width: "1em",
              height: "1em",
              color: "#A7C0EA",
            }}
          />
        </div>
      </div>

      <div className={styles.bannerPaginaInicial}>
        <div className={styles.bannerOverlayPaginaInicial}></div>
        <Image
          className={styles.bannerPaginaInicial}
          src={banner.src}
          alt="Chápeu do Mario"
        />
        <h1>{banner.title}</h1>
        <p>{banner.description}</p>

        <button>Super Mario</button>
      </div>

      <div className={styles.conteudo}>
  {marioFiltrado.length > 0 && (
    <>
      <h1>Super Mario</h1>
      <div className={styles.conteudoContainer}>
        {marioFiltrado.map((item, index) => (
          <div className={styles.conteudoItem} key={index}>
            <Image
              className={styles.imagens}
              src={item.src}
              alt={item.text}
              width={item.width}
              height={item.height}
            />
            <p>{item.text}</p>
            <p>{item.price}</p>
          </div>
        ))}
      </div>
    </>
  )}

  {consolesFiltrados.length > 0 && (
    <>
      <h1>Consoles</h1>
      <div className={styles.conteudoContainer}>
        {consolesFiltrados.map((item, index) => (
          <div className={styles.conteudoItem} key={index}>
            <Image
              className={styles.imagens}
              src={item.src}
              alt={item.text}
              width={item.width}
              height={item.height}
            />
            <p>{item.text}</p>
            <p>{item.price}</p>
          </div>
        ))}
      </div>
    </>
  )}

  {diversosFiltrados.length > 0 && (
    <>
      <h1>Diversos</h1>
      <div className={styles.conteudoContainer}>
        {diversosFiltrados.map((item, index) => (
          <div className={styles.conteudoItem} key={index}>
            <Image
              className={styles.imagens}
              src={item.src}
              alt={item.text}
              width={item.width}
              height={item.height}
            />
            <p>{item.text}</p>
            <p>{item.price}</p>
          </div>
        ))}
      </div>
    </>
  )}

  {marioFiltrado.length === 0 &&
    consolesFiltrados.length === 0 &&
    diversosFiltrados.length === 0 && (
      <p>Nenhum resultado encontrado</p>
    )}


        <div className="rodape">
          <Link className="cabecalho_linkPaginaINicial" href="/">
            <Icon color="#628FD9" width="3rem" icon="ph:game-controller" />
            <h1>
              Player<span>One</span>
            </h1>
          </Link>

          <h4>
            Desenvolvido por{" "}
            <Link
              className="linkRodape"
              href="https://www.linkedin.com/in/isis-souza-979163295/"
            >
              {" "}
              Isis Guimarães{" "}
            </Link>
            | 2023
          </h4>
        </div>
      </div>
    </header>
  );
}
